### PR TITLE
Moved application source files in their own src directory.

### PR DESCRIPTION
**Pull request by redtide**
Changed Makefile and ui|irc/util.hpp for the new directory tree.

### CODE REVIEW

**Comment by jgouly** [comment]
LGTM. I would also prefer an include/ folder too, for the public headers.

**Comment by redtide** [comment]
Sorry, I thought you wanted to do that in a later moment from what I recall from yesterday IRC discussion
(following your pastebin dir structure).
I don't know much your application but if it's not something to include in another one, I don't think we really need an include directory for it, but just for irc and ui libs.

**Comment by jgouly** [comment]
I'm not the author by the way! Just giving my thoughts. As I recall, some parts, like the irc core are meant to be usable by other libraries, but for now, putting stuff in src is a good step.

**Comment by dobson156** [comment]
Joey, the irc and ui directories will at some point soon become sub modules.

And of course the actual application code can itself be broken down further too.

**Pull request merged**
